version: '3.7'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: imemreg.azurecr.io/myapp-server
    container_name: myapp-node-server
    command: npm start
    volumes:
      - ./server/:/usr/src/app
    ports:
      - "5000:5000"
    env_file: ./server/.env
    environment:
      - NODE_ENV=development
    networks:
      - app-network
  client:
    build:
      context: ./client
      dockerfile: Dockerfile-Dev
    image: imemreg.azurecr.io/myapp-client
    container_name: myapp-react-client
    command: npm start
    volumes:
      - ./client/:/usr/app
    depends_on:
      - server
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
    app-network:
        driver: bridge

volumes:
    data-volume:
    node_modules:
    web-root:
      driver: local